version: 0.1.{build}

image: Visual Studio 2015

environment:
  matrix:
    # Python 3.5.3 - 64-bit
    - PYTHON: "C:\\Python35-x64"

#---------------------------------#
#        Build                    #
#---------------------------------#

build: off

configuration: Release

install:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%;C:\MinGW\bin;C:\Python35-x64\Scripts
  - copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
  - copy c:\Python35-x64\python.exe c:\Python35-x64\python3.exe
  - python -m pip install --upgrade pip
  - appveyor DownloadFile -filename vcredist2010_x64.exe https://download.microsoft.com/download/A/8/0/A80747C3-41BD-45DF-B505-E9710D2744E0/vcredist_x64.exe
  - vcredist2010_x86.exe /passive /norestart
  - appveyor DownloadFile -filename vcredist2017_x64.exe https://aka.ms/vs/15/release/VC_redist.x64.exe
  - vcredist2017_x64.exe /passive /norestart
  - python --version
  - make install

after_test:
  - make package
  - '7z a DEXBot-gui-win64.zip %APPVEYOR_BUILD_FOLDER%\dist\DEXBot-gui.exe'

# @TODO: Run tests..
test_script:
  - "echo tests..."

artifacts:
  - path: DEXBot-gui-win64.zip
    name: DEXBot-gui-win64.zip

#---------------------------------#
#        Deployment               #
#---------------------------------#

shallow_clone: false

clone_depth: 1

deploy:
  - provider: GitHub
    draft: false
    prerelease: false
    force_update: true
    auth_token:
      secure: 9qvwlVUHFBV4GwMz1Gu2HSnqU8Ex2nv5dsY4mVNCurrb+6ULIoHPgbvJPWTo3qV6
    on:
      appveyor_repo_tag: true     # deploy on tag push only

#---------------------------------#
#         Notifications           #
#---------------------------------#

#notifications:
#  - provider: Slack
#    auth_token:
#      secure: G9OMj9l2s3+lX8cRiNXXhuQJpnnjcBc0cqP8gzkdKVWqGA8vBTOIPGxD/536VKpeBH/5dJFQWT+vmnGS+XciaCg4hh5s6hDpnvePq2+uEYE=
#    channel: '#ci'
